// Reset data
export const ADMIN_RESET = 'ADMIN_RESET';

// Prerequisites
export const ADMIN_PREREQUISITES_UPDATE = 'ADMIN_PREREQUISITES_UPDATE';
export const ADMIN_GET_BASIC_SALES_STATUS_DETAIL = 'ADMIN_GET_BASIC_SALES_STATUS_DETAIL';


/*
 * Pending
 */
//User address detail
export const ADMIN_GET_ADDRESS_DETAIL = 'ADMIN_GET_ADDRESS_DETAIL';
export const ADMIN_GET_NBA_DETAIL = 'ADMIN_GET_NBA_DETAIL';

/*
 * Group management
 */
// User hierarchy
export const ADMIN_GET_USER_HIERARCHY = 'ADMIN_GET_USER_HIERARCHY';
export const ADMIN_RESET_USER_HIERARCHY = 'ADMIN_RESET_USER_HIERARCHY';

// Group
export const ADMIN_GET_GROUP_DETAIL = 'ADMIN_GET_GROUP_DETAIL';

/*
 * Transactions management
 */
// Transactions
export const ADMIN_GET_TRANSACTION_DETAIL = 'ADMIN_GET_TRANSACTION_DETAIL';
export const ADMIN_UPDATE_TRANSACTION_STATUS = 'ADMIN_UPDATE_TRANSACTION_STATUS';
export const ADMIN_GET_TRANSACTION_FORM_DETAIL = 'ADMIN_GET_TRANSACTION_FORM_DETAIL';
export const ADMIN_RESET_TRANSACTION_FORM_DETAIL = 'ADMIN_RESET_TRANSACTION_FORM_DETAIL';

// IB list
export const ADMIN_GET_IB_DETAIL = 'ADMIN_GET_IB_DETAIL';
export const ADMIN_IB_DETAIL_REBATE_ACCOUNT_REMOVE = 'ADMIN_IB_DETAIL_REBATE_ACCOUNT_REMOVE';
export const ADMIN_GET_TRADING_CLIENT_DETAIL = 'ADMIN_GET_TRADING_CLIENT_DETAIL';
export const ADMIN_RESET_TRADING_CLIENT_DETAIL = 'ADMIN_RESET_TRADING_CLIENT_DETAIL';

// Rebate accounts
export const ADMIN_GET_REBATE_ACCOUNT_ADD_FORM_DETAIL = 'ADMIN_GET_REBATE_ACCOUNT_ADD_FORM_DETAIL';
export const ADMIN_RESET_REBATE_ACCOUNT_ADD_FORM_DETAIL = 'ADMIN_RESET_REBATE_ACCOUNT_ADD_FORM_DETAIL';

// Commission level
export const ADMIN_GET_REBATE_ACCOUNT_COMMISSION_LEVEL_FORM_DETAIL = 'ADMIN_GET_REBATE_ACCOUNT_COMMISSION_LEVEL_FORM_DETAIL';
export const ADMIN_RESET_REBATE_ACCOUNT_COMMISSION_LEVEL_FORM_DETAIL = 'ADMIN_RESET_REBATE_ACCOUNT_COMMISSION_LEVEL_FORM_DETAIL';
