//Reset data
export const DATA_RESET = 'DATA_RESET';

//Prerequisites
export const DATA_PREREQUISITES_UPDATE = 'DATA_PREREQUISITES_UPDATE';

/*
 * User account management
 */
//User profile
export const DATA_GET_USER_PROFILE = 'DATA_GET_USER_PROFILE';

//User addresses
export const DATA_GET_USER_ADDRESSES = 'DATA_GET_USER_ADDRESSES';

//User documents
export const DATA_GET_USER_DOCUMENTS = 'DATA_GET_USER_DOCUMENTS';
export const DATA_SUPPORTING_DOCUMENT_UPDATE = 'DATA_SUPPORTING_DOCUMENT_UPDATE';

//Referral links
export const DATA_GET_REFERRAL_LINKS = 'DATA_GET_REFERRAL_LINKS';

/*
 * Funding
 */
//Nominated bank account
export const DATA_GET_NOMINATED_BANK_ACCOUNTS = 'DATA_GET_NOMINATED_BANK_ACCOUNTS';

//Link trading accounts
export const DATA_GET_LINKED_TRADING_ACCOUNTS = 'DATA_GET_LINKED_TRADING_ACCOUNTS';
export const DATA_GET_REBATE_ACCOUNTS = 'DATA_GET_REBATE_ACCOUNTS';
export const DATA_GET_REBATE_ACCOUNT_RATE_TABLE = 'DATA_GET_REBATE_ACCOUNT_RATE_TABLE';
export const DATA_GET_REBATE_ACCOUNTS_UNASSIGNED = 'DATA_GET_REBATE_ACCOUNTS_UNASSIGNED';
