import { getTranslation } from '../../custom/Libraries/Utility';

// Fields namespace
let i18nNameSpace = 2;

// Form params
export const BasicField = {
    accountHolderAddress: {
        lang: getTranslation('accountHolderAddress', i18nNameSpace),
        name: 'account_holder_address',
        type: 'text',
        rules: 'required|max:500',
    },
    adjustmentAmount: {
        lang: getTranslation('adjustmentAmount', i18nNameSpace),
        name: 'amount',
        type: 'number',
        rules: 'required',
    },
    adjustmentCurrency: {
        lang: getTranslation('adjustmentCurrency', i18nNameSpace),
        name: 'adjustment_currency',
        type: 'text',
        rules: 'required',
    },
    adjustmentDate: {
        lang: getTranslation('adjustmentDate', i18nNameSpace),
        name: 'adjustment_date',
        type: 'text',
        rules: 'required',
    },
    adjustmentDeclaration: {
        lang: getTranslation('adjustmentDeclaration', i18nNameSpace),
        name: 'declaration',
        type: 'text',
        rules: 'required',
    },
    adjustmentReason: {
        lang: getTranslation('adjustmentReason', i18nNameSpace),
        name: 'notes',
        type: 'textarea',
        rules: 'required|min:5',
    },
    adjustmentType: {
        lang: getTranslation('adjustmentType', i18nNameSpace),
        name: 'basics_account_journal_transaction_type_id',
        type: 'select',
        rules: 'required',
    },
    amount: {
        lang: getTranslation('amount', i18nNameSpace),
        name: 'amount',
        type: 'number',
        rules: 'required',
    },
    bankName: {
        lang: getTranslation('bankName', i18nNameSpace),
        name: 'bank_name',
        type: 'text',
        rules: 'required',
    },
    bankAddress: {
        lang: getTranslation('bankAddress', i18nNameSpace),
        name: 'bank_address',
        type: 'textarea',
        rules: 'required',
    },
    basicCurrency: {
        lang: getTranslation('basicCurrency', i18nNameSpace),
        name: 'basics_currency_id',
        type: 'select',
        rules: 'required',
    },
    basicRebateCommissionLevel: {
        lang: getTranslation('basicRebateCommissionLevel', i18nNameSpace),
        name: 'basics_rebate_commission_level_id',
        type: 'select',
        rules: 'required',
    },
    basicRebateCommissionLevelCurrent: {
        lang: getTranslation('basicRebateCommissionLevelCurrent', i18nNameSpace),
        name: 'basics_rebate_commission_level_current',
        type: 'text',
        rules: 'required',
    },
    basicTradingPlatform: {
        lang: getTranslation('basicTradingPlatform', i18nNameSpace),
        name: 'basics_trading_platform_id',
        type: 'select',
        rules: 'required',
    },
    bsbCode: {
        lang: getTranslation('bsbCode', i18nNameSpace),
        name: 'bsb_code',
        type: 'text',
        rules: 'required',
    },
    beneficiaryAccountNumber: {
        lang: getTranslation('beneficiaryAccountNumber', i18nNameSpace),
        name: 'beneficiary_account_number',
        type: 'text',
        rules: 'required',
    },
    beneficiaryAccountName: {
        lang: getTranslation('beneficiaryAccountName', i18nNameSpace),
        name: 'beneficiary_account_name',
        type: 'text',
        rules: 'required|max:100',
    },
    city: {
        lang: getTranslation('city', i18nNameSpace),
        name: 'city',
        type: 'text',
        rules: 'required',
    },
    confirmEmail: {
        lang: getTranslation('confirmEmail', i18nNameSpace),
        name: 'confirm_email',
        type: 'email',
        rules: 'required|email|same:email',
    },
    country: {
        lang: getTranslation('country', i18nNameSpace),
        name: 'country',
        type: 'text',
        rules: 'required',
    },
    selectedCountry: {
        lang: getTranslation('selectedCountry', i18nNameSpace),
        name: 'selected_country',
        type: 'text',
        rules: 'required',
    },
    countryProfile: {
        lang: getTranslation('countryProfile', i18nNameSpace),
        name: 'country',
        type: 'text',
        rules: 'required',
    },
    currency: {
        lang: getTranslation('currency', i18nNameSpace),
        name: 'currency',
        type: 'text',
        rules: 'max:100',
    },
    currentRefereeRebateAccountNumber: {
        lang: getTranslation('currentRefereeRebateAccountNumber', i18nNameSpace),
        name: 'current_referee_rebate_account_number',
        type: 'text',
        rules: 'required',
    },
    currentRefereeIbName: {
        lang: getTranslation('currentRefereeIbName', i18nNameSpace),
        name: 'current_referee_ib_name',
        type: 'text',
        rules: 'required',
    },
    destroyDeclaration: {
        lang: getTranslation('destroyDeclaration', i18nNameSpace),
        name: 'declaration',
        type: 'text',
        rules: 'required',
    },
    dob: {
        lang: getTranslation('dob', i18nNameSpace),
        name: 'dob',
        type: 'text',
        rules: 'required|date',
    },
    document: {
        lang: getTranslation('document', i18nNameSpace),
        name: 'attachments',
        type: 'file',
        rules: 'required',
    },
    documentType: {
        lang: getTranslation('documentType', i18nNameSpace),
        name: 'document_id',
        type: 'select',
        rules: 'required',
    },
    email: {
        lang: getTranslation('email', i18nNameSpace),
        name: 'email',
        type: 'email',
        rules: 'required|email',
    },
    entityType: {
        lang: getTranslation('entityType', i18nNameSpace),
        name: 'entity_type',
        type: 'text',
        rules: 'required',
    },
    firstName: {
        lang: getTranslation('firstName', i18nNameSpace),
        name: 'first_name',
        type: 'text',
        rules: 'required',
    },
    file: {
        lang: getTranslation('file', i18nNameSpace),
        name: 'attachment',
        type: 'file',
        rules: 'required',
    },
    fromRebateAccount: {
        lang: getTranslation('fromRebateAccount', i18nNameSpace),
        name: 'from_account_id',
        type: 'select',
        rules: 'required',
    },
    fullName: {
        lang: getTranslation('fullName', i18nNameSpace),
        name: 'full_name',
        type: 'text',
        rules: 'required',
    },
    ibName: {
        lang: getTranslation('ibName', i18nNameSpace),
        name: 'ib_name',
        type: 'text',
        rules: 'required',
    },
    lastName: {
        lang: getTranslation('lastName', i18nNameSpace),
        name: 'last_name',
        type: 'text',
        rules: 'required',
    },
    otp: {
        lang: getTranslation('otp', i18nNameSpace),
        name: 'otp',
        type: 'text',
        rules: 'required|numeric',
    },
    password: {
        lang: getTranslation('password', i18nNameSpace),
        name: 'password',
        type: 'password',
        rules: 'required|min:8|max:20',
    },
    passwordConfirm: {
        lang: getTranslation('passwordConfirm', i18nNameSpace),
        name: 'confirm_password',
        type: 'password',
        rules: 'required|same:password',
    },
    passwordNew: {
        lang: getTranslation('passwordNew', i18nNameSpace),
        name: 'password',
        type: 'password',
        rules: 'required|min:8|max:20',
    },
    passwordOld: {
        lang: getTranslation('passwordOld', i18nNameSpace),
        name: 'old_password',
        type: 'password',
        rules: 'required|min:8|max:20',
    },
    phone: {
        lang: getTranslation('phone', i18nNameSpace),
        name: 'phone',
        type: 'number',
        rules: 'required',
    },
    phoneCode: {
        lang: getTranslation('phoneCode', i18nNameSpace),
        name: 'phone_code',
        type: 'text',
        rules: 'required',
    },
    selectedPhoneCode: {
        lang: getTranslation('selectedPhoneCode', i18nNameSpace),
        name: 'selected_phone_code',
        type: 'text',
    },
    photoIdentification: {
        lang: getTranslation('photoIdentification', i18nNameSpace),
        name: 'attachment',
        type: 'file',
        rules: 'required',
    },
    postalCode: {
        lang: getTranslation('postalCode', i18nNameSpace),
        name: 'postal_code',
        type: 'text',
        rules: 'required',
    },
    rebateAccount: {
        lang: getTranslation('rebateAccount', i18nNameSpace),
        name: 'rebate_account_id',
        type: 'select',
        rules: 'required',
    },
    rebateAccountAddDeclaration: {
        lang: getTranslation('rebateAccountAddDeclaration', i18nNameSpace),
        name: 'declaration',
        type: 'text',
        rules: 'required',
    },
    rebateAccountChangeReason: {
        lang: getTranslation('rebateAccountChangeReason', i18nNameSpace),
        name: 'basics_rebate_account_change_reason_id',
        type: 'select',
        rules: 'required',
    },
    rebateAccountNumber: {
        lang: getTranslation('rebateAccountNumber', i18nNameSpace),
        name: 'ib_rebate_account_id',
        type: 'text',
        rules: 'required',
    },
    rebateAccountSearch: {
        lang: getTranslation('rebateAccountSearch', i18nNameSpace),
        name: 'ib_rebate_account_code',
        type: 'text',
        rules: 'required',
    },
    rebateCalculationType: {
        lang: getTranslation('rebateCalculationType', i18nNameSpace),
        name: 'rebate_calculation_type_id',
        type: 'select',
        rules: 'required',
    },
    rebateRateTableType: {
        lang: getTranslation('rebateRateTableType', i18nNameSpace),
        name: 'rebate_rate_table_type_id',
        type: 'select',
        rules: 'required',
    },
    region: {
        lang: getTranslation('region', i18nNameSpace),
        name: 'region',
        type: 'text',
        rules: 'required',
    },
    regionRefer: {
        lang: getTranslation('regionRefer', i18nNameSpace),
        name: 'region',
        type: 'text',
        rules: 'required',
    },
    state: {
        lang: getTranslation('state', i18nNameSpace),
        name: 'state',
        type: 'text',
        rules: 'required',
    },
    streetName: {
        lang: getTranslation('streetName', i18nNameSpace),
        name: 'street_address',
        type: 'text',
        rules: 'required',
    },
    swift: {
        lang: getTranslation('swift', i18nNameSpace),
        name: 'swift',
        type: 'text',
        rules: 'required|max:100',
    },
    termsAcceptance: {
        lang: getTranslation('termsAcceptance', i18nNameSpace),
        name: 'terms_acceptance',
        type: 'text',
        rules: 'required',
    },
    toNominatedBankAccount: {
        lang: getTranslation('toNominatedBankAccount', i18nNameSpace),
        name: 'to_account_id',
        type: 'select',
        rules: 'required',
    },
    toRebateAccount: {
        lang: getTranslation('toRebateAccount', i18nNameSpace),
        name: 'to_account_id',
        type: 'select',
        rules: 'required',
    },
    toTradingAccount: {
        lang: getTranslation('toTradingAccount', i18nNameSpace),
        name: 'to_account_id',
        type: 'select',
        rules: 'required',
    },
    town: {
        lang: getTranslation('town', i18nNameSpace),
        name: 'town',
        type: 'text',
        rules: 'required',
    },
    tradingAccountNumber: {
        lang: getTranslation('tradingAccountNumber', i18nNameSpace),
        name: 'trading_account_number',
        type: 'text',
        rules: 'required',
    },
    tradingClientSearch: {
        lang: getTranslation('tradingClientSearch', i18nNameSpace),
        name: 'fpm_trading_client_account_code',
        type: 'text',
        rules: 'required',
    },
    tradingCurrency: {
        lang: getTranslation('tradingCurrency', i18nNameSpace),
        name: 'currency_id',
        type: 'select',
        rules: 'required',
    },
    tradingCurrencyMulti: {
        lang: getTranslation('tradingCurrencyMulti', i18nNameSpace),
        name: 'trading_currencies',
        type: 'select',
        rules: 'required',
    },
    tradingPlatform: {
        lang: getTranslation('tradingPlatform', i18nNameSpace),
        name: 'trading_platform_id',
        type: 'select',
        rules: 'required',
    },
    tradingProduct: {
        lang: getTranslation('tradingProduct', i18nNameSpace),
        name: 'trading_product_id',
        type: 'select',
        rules: 'required',
    },
    tradingProductMulti: {
        lang: getTranslation('tradingProductMulti', i18nNameSpace),
        name: 'trading_products',
        type: 'select',
        rules: 'required|array',
    },
    tradingProductMultiRebateCalculationType: {
        lang: null,
        name: 'trading_products.*.rebate_calculation_type_id',
        type: 'select',
        rules: 'required',
    },
    tradingProductMultiTradingProduct: {
        lang: null,
        name: 'trading_products.*.trading_product_id',
        type: 'select',
        rules: 'required',
    },
    transactionType: {
        lang: getTranslation('transactionType', i18nNameSpace),
        name: 'basics_reference_class_id',
        type: 'select',
        rules: 'required',
    },
    unitNumber: {
        lang: getTranslation('unitNumber', i18nNameSpace),
        name: 'unit_number',
        type: 'text',
        rules: 'required',
    },
    updateDate: {
        lang: getTranslation('updateDate', i18nNameSpace),
        name: 'update_date',
        type: 'text',
        rules: 'required',
    },
    updateDeclaration: {
        lang: getTranslation('updateDeclaration', i18nNameSpace),
        name: 'declaration',
        type: 'text',
        rules: 'required',
    },
    uploadReason: {
        lang: getTranslation('uploadReason', i18nNameSpace),
        name: 'upload_reason_id',
        type: 'select',
        rules: 'required',
    },
    userIdNumber: {
        lang: getTranslation('userIdNumber', i18nNameSpace),
        name: 'user_id',
        type: 'text',
        rules: 'required',
    },
    userLevel: {
        lang: getTranslation('userLevel', i18nNameSpace),
        name: 'user_level_id',
        type: 'select',
        rules: 'required',
    },
    userLevelThreeSelection: {
        lang: getTranslation('userLevelThreeSelection', i18nNameSpace),
        name: 'user_level_3_selections',
        type: 'text',
        rules: 'numeric',
    },
    userLevelThreeSelectionView: {
        lang: getTranslation('userLevelThreeSelectionView', i18nNameSpace),
        name: 'user_level_3_selections_view',
        type: 'text',
        rules: 'string',
    },
    userLevelFourSelection: {
        lang: getTranslation('userLevelFourSelection', i18nNameSpace),
        name: 'user_level_4_selections',
        type: 'text',
        rules: 'numeric',
    },
    userLevelFourSelectionView: {
        lang: getTranslation('userLevelFourSelectionView', i18nNameSpace),
        name: 'user_level_4_selections_view',
        type: 'text',
        rules: 'string',
    },
    userLevelFiveSelection: {
        lang: getTranslation('userLevelFiveSelection', i18nNameSpace),
        name: 'user_level_5_selections',
        type: 'text',
        rules: 'numeric',
    },
    userLevelFiveSelectionView: {
        lang: getTranslation('userLevelFiveSelectionView', i18nNameSpace),
        name: 'user_level_5_selections_view',
        type: 'text',
        rules: 'string',
    },
    userLevelSixSelection: {
        lang: getTranslation('userLevelSixSelection', i18nNameSpace),
        name: 'user_level_6_selections',
        type: 'text',
        rules: 'numeric',
    },
    userLevelSixSelectionView: {
        lang: getTranslation('userLevelSixSelectionView', i18nNameSpace),
        name: 'user_level_6_selections_view',
        type: 'text',
        rules: 'string',
    },
    userLevelSevenSelection: {
        lang: getTranslation('userLevelSevenSelection', i18nNameSpace),
        name: 'user_level_7_selections',
        type: 'text',
        rules: 'numeric',
    },
    userLevelSevenSelectionView: {
        lang: getTranslation('userLevelSevenSelectionView', i18nNameSpace),
        name: 'user_level_7_selections_view',
        type: 'text',
        rules: 'string',
    },
    userLevelEightSelection: {
        lang: getTranslation('userLevelEightSelection', i18nNameSpace),
        name: 'user_level_8_selections',
        type: 'text',
        rules: 'numeric',
    },
    userLevelEightSelectionView: {
        lang: getTranslation('userLevelEightSelectionView', i18nNameSpace),
        name: 'user_level_8_selections_view',
        type: 'text',
        rules: 'string',
    },
    userComment: {
        lang: getTranslation('userComment', i18nNameSpace),
        name: 'comment',
        type: 'textarea',
        rules: 'string|min:5|max:500',
    },
    salesStatus: {
        lang: getTranslation('salesStatus', i18nNameSpace),
        name: 'sales_status',
        type: 'select',
        rules: 'string',
    },
    companyName: {
        lang: getTranslation('companyName', i18nNameSpace),
        name: 'company_name',
        type: 'text',
        rules: 'string',
    },
};

export default BasicField;
